/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExportIndexImport } from './routes/export/index'
import { Route as ReportIdIndexImport } from './routes/$reportId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExportIndexRoute = ExportIndexImport.update({
  path: '/export/',
  getParentRoute: () => rootRoute,
} as any)

const ReportIdIndexRoute = ReportIdIndexImport.update({
  path: '/$reportId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$reportId/': {
      id: '/$reportId/'
      path: '/$reportId'
      fullPath: '/$reportId'
      preLoaderRoute: typeof ReportIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/export/': {
      id: '/export/'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ReportIdIndexRoute,
  ExportIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$reportId/",
        "/export/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$reportId/": {
      "filePath": "$reportId/index.tsx"
    },
    "/export/": {
      "filePath": "export/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
