/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReportsReportsIdIndexImport } from './routes/reports/$reportsId/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ReportsReportsIdIndexRoute = ReportsReportsIdIndexImport.update({
  path: '/reports/$reportsId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/reports/$reportsId/': {
      id: '/reports/$reportsId/'
      path: '/reports/$reportsId'
      fullPath: '/reports/$reportsId'
      preLoaderRoute: typeof ReportsReportsIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ReportsReportsIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/reports/$reportsId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/reports/$reportsId/": {
      "filePath": "reports/$reportsId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
